name: Build Firmware

on:
  push:
    branches: [ "cli", "main", "master" ]
  pull_request:
    branches: [ "cli", "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install PlatformIO Core
      run: pip install --upgrade platformio

    - name: Build Firmware
      working-directory: ./firmware
      run: pio run
